### 第九章 使用 NumPy 套件

#### 9.1 初探 NumPy 陣列

##### 9.1.1 NumPy 陣列的基本認識

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4])

In [3]:
a.ndim

1

In [4]:
a.shape

(5,)

In [5]:
a.dtype

dtype('int64')

In [6]:
print(a)

[0 1 2 3 4]


In [7]:
a

array([0, 1, 2, 3, 4])

In [8]:
np.array([12]).shape

(1,)

In [9]:
np.array(12).shape

()

In [10]:
np.array(12).ndim

0

In [11]:
a = np.array([[1, 3, 2],[4, 7, 9]])

In [12]:
print(a)

[[1 3 2]
 [4 7 9]]


In [13]:
a

array([[1, 3, 2],
       [4, 7, 9]])

In [14]:
a.ndim

2

In [15]:
a.shape

(2, 3)

In [16]:
a.size

6

In [17]:
a = np.array([[[1, 2, 3, 0],
               [3, 4, 5, 0],
               [5, 6, 7, 1]],

              [[7, 8, 9, 1],
               [8, 2, 2, 1],
               [1, 2, 4, 6]]])

In [18]:
print(a)

[[[1 2 3 0]
  [3 4 5 0]
  [5 6 7 1]]

 [[7 8 9 1]
  [8 2 2 1]
  [1 2 4 6]]]


In [19]:
a.ndim

3

In [20]:
a.shape

(2, 3, 4)

In [21]:
a.size

24

##### 9.1.2 NumPy 常用的資料型別

In [22]:
np.array([1,2,3],dtype='float64')

array([1., 2., 3.])

In [23]:
np.array([0, 1, 4], dtype=bool)

array([False,  True,  True])

In [24]:
a=np.array([[1.2,4.0],[6.9,8.3]])

In [25]:
a.astype('int32')

array([[1, 4],
       [6, 8]], dtype=int32)

In [26]:
a.dtype

dtype('float64')

In [27]:
a.tolist()

[[1.2, 4.0], [6.9, 8.3]]

In [28]:
a = np.array(['Tom','Jerry'])

In [29]:
print(a.dtype)

<U5


In [30]:
np.array(['T',5])

array(['T', '5'], dtype='<U21')

In [31]:
np.array(['T',5], dtype=object)

array(['T', 5], dtype=object)

##### 9.1.3 用來建立陣列的函數

In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [37]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.ones(3, dtype='int32')

array([1, 1, 1], dtype=int32)

In [39]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
np.tile([[1,2],[3,4]],(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

##### 9.1.4 產生亂數

In [42]:
np.random.seed(999)

In [43]:
p = np.random.randint(1, 7, (2, 3))
print(p)

[[1 5 6]
 [2 1 2]]


In [44]:
print(np.random.rand(3, 2))

[[0.63968144 0.09092526]
 [0.33222568 0.42738095]
 [0.55438581 0.62812652]]


In [45]:
print(np.random.randn(3, 1))

[[ 0.98433937]
 [ 0.67012194]
 [-0.37051232]]


In [46]:
rg = np.random.default_rng(998)

In [47]:
print(rg.integers(3, 5, (2, 6)))

[[4 4 3 3 3 4]
 [3 3 4 4 4 4]]


In [48]:
rg.choice(range(5), 4)

array([4, 3, 0, 4])

In [49]:
rg.choice(range(5),4,
    replace=False)

array([3, 0, 1, 4])

In [50]:
# ch9_1.py, permutation()和shuffle()的差異
import numpy as np
rg = np.random.default_rng()   		# 建立亂數生成器

arr = np.array([1, 2, 3, 4]) 			# 初始化一個陣列
permuted_arr = rg.permutation(arr)  	# 使用permutation ()
print('permutation() 產生的新陣列：', permuted_arr)
print('permutation() 後的原始陣列：', arr)  	
 
arr = np.array([1, 2, 3, 4]) 			# 重新初始化陣列
rg.shuffle(arr) 						# 使用 shuffle()
print('shuffle() 打亂後的原始陣列：', arr)

permutation() 產生的新陣列： [2 1 4 3]
permutation() 後的原始陣列： [1 2 3 4]
shuffle() 打亂後的原始陣列： [3 4 2 1]


In [51]:
# ch9_2.py, 使用 choice() 抽查學生成績
import numpy as np
rg = np.random.default_rng()   # 建立隨機數生成器
data = np.array([    # 建立二維陣列，包含學生姓名和單科成績
    ['Alice', 85],
    ['Bob', 92],
    ['Cathy', 78],
    ['David', 90],
])
# 從學生資料中隨機抽查 2 位學生的成績，不重複抽樣 
result = rg.choice(data, size=2, replace=False, axis=0) 
print(result)

[['Bob' '92']
 ['Cathy' '78']]


#### 9.2 陣列元素的提取

##### 9.2.1 利用索引提取陣列元素

In [52]:
a=np.array([3, 8, 9, 7])

In [53]:
a[0], a[-1]

(np.int64(3), np.int64(7))

In [54]:
b = np.array([[3, 4, 5, 7],
              [6, 8, 1, 0],
              [8, 9, 3, 4]])

In [55]:
b[0]

array([3, 4, 5, 7])

In [56]:
b[0][2]

np.int64(5)

In [57]:
b[-1]

array([8, 9, 3, 4])

In [60]:
b[-1] = [1, 2, 9, 9]

In [61]:
b

array([[3, 4, 5, 7],
       [6, 8, 1, 0],
       [1, 2, 9, 9]])

##### 9.2.2 陣列的切片操作

In [62]:
a = np.array([10, 16, 32, 17, 20])

In [63]:
a[:3]

array([10, 16, 32])

In [64]:
a[1:4]

array([16, 32, 17])

In [65]:
a[2:]

array([32, 17, 20])

In [66]:
a[::-1]

array([20, 17, 32, 16, 10])

In [67]:
a[2::-1]

array([32, 16, 10])

In [68]:
a = np.array([[0, 1, 2, 3],
              [6, 7, 8, 9],
              [12, 13, 14, 15]])

In [69]:
a[1, 2:]

array([8, 9])

In [70]:
a[0, ::-1]

array([3, 2, 1, 0])

In [71]:
print(a[1:, :])

[[ 6  7  8  9]
 [12 13 14 15]]


In [72]:
print(a[:,2])

[ 2  8 14]


In [73]:
print(a[:,2:3])

[[ 2]
 [ 8]
 [14]]


In [74]:
print(a[:2])

[[0 1 2 3]
 [6 7 8 9]]


##### 9.2.3 利用布林陣列提取元素

In [75]:
a = np.array([22, 65, 36])

In [76]:
a[[True, False, True]]

array([22, 36])

In [77]:
b = np.array([[1, 2, 3],
              [2, 6, 4]])

In [78]:
b>3

array([[False, False, False],
       [False,  True,  True]])

In [79]:
b[b>3]

array([6, 4])

In [80]:
b[:, [True, False, True]]

array([[1, 3],
       [2, 4]])

##### 9.2.4 利用整數陣列提取元素

In [81]:
a = np.array([9, 17, 23, 34, 45])

In [82]:
a[[0, 2, 2]]

array([ 9, 23, 23])

In [83]:
idx = np.array([[2, 0, 3],
                [1, 3, 4]])

In [84]:
a[idx]

array([[23,  9, 34],
       [17, 34, 45]])

In [85]:
a = np.array([[6, 3, 4, 2],
              [3, 1, 4, 8],
              [1, 5, 3, 7]])

In [104]:
a[[0, 2, 1],[3, 1, 2]]

array([2, 5, 4])

In [105]:
a[1:3, [3, 2]]

array([[8, 4],
       [7, 3]])

In [106]:
a[[True, False, True], 1:]

array([[3, 4, 2],
       [5, 3, 7]])

In [86]:
# ch9_3.py, 陣列提取的應用
import numpy as np
scores = np.array([		# 每行分別是國文、英文、數學和自然成績
    [72, 88, 91, 65],		# Tom
    [85, 67, 78, 90],		# Jerry
    [60, 75, 80, 70]		# Mary
])
names = np.array(['Tom', 'Jerry', 'Mary'])
 
print('Jerry的數學成績:', scores[1, 2])  # 索引
print('Tom和Jerry的國文、英文成績:\n', scores[0:2, 0:2])  # 切片
 
print('Tom和Mary的自然成績:', scores[[0, 2],[3, 3]])     # 花式
 
# 布林陣列：找出數學成績大於 80 的學生
mask = scores[:, 2] > 80		# mask的值為 [True False False]
print('Math > 80:', names[mask])

Jerry的數學成績: 78
Tom和Jerry的國文、英文成績:
 [[72 88]
 [85 67]]
Tom和Mary的自然成績: [65 70]
Math > 80: ['Tom']


##### 9.2.5 拷貝與檢視

In [87]:
# ch9_4.py, 拷貝與檢視的比較
import numpy as np
a = np.array([8, 6, 0, 9, 1, 9])    	# 初始化一維陣列 a
s = a[1:4]   					# 切片取出 [6, 0, 9]，這是 View
s[0] = 99  					# 修改 s[0]，會影響原始陣列 a[1]
print('切片結果 s：', s)  		# s 變為 [99, 0, 9]
print('原始陣列 a：', a)  		# a[1] 被改為 99
 
a = np.array([8, 6, 0, 9, 1, 9])  		# 重新初始化 a 
f = a[[1, 2, 3]]   			# 花式索引取出 [6, 0, 9]，這是 Copy
f[0] = 77  					# 修改 f[0]，不會影響原始陣列 a[1]
print('花式索引結果 f：', f)  	# f 變為 [77, 0, 9]
print('原始陣列 a：', a)  		# a[1] 保持不變

切片結果 s： [99  0  9]
原始陣列 a： [ 8 99  0  9  1  9]
花式索引結果 f： [77  0  9]
原始陣列 a： [8 6 0 9 1 9]


In [88]:
a = np.array([1, 2, 3])

In [89]:
b=a[1:]; c=a[[True, False, False]]

In [90]:
np.shares_memory(a, b)

True

In [91]:
np.shares_memory(a, c)

False

In [93]:
d = a[1:].copy()

In [94]:
np.shares_memory(a, d)

False

#### 9.3 陣列的進階處理

##### 9.3.1 拆平與重排

In [96]:
a=np.array([1, 2, 3, 4, 5, 6])

In [97]:
b=a.reshape(3, 2); print(b)

[[1 2]
 [3 4]
 [5 6]]


In [98]:
c = b.T; print(c)

[[1 3 5]
 [2 4 6]]


In [99]:
np.shares_memory(a, b)

True

In [100]:
np.shares_memory(a, c)

True

In [101]:
a.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
# ch9_5.py, ravel() 和 flatten() 的區別
import numpy as np
a = np.array([[1, 2], [3, 4]])  		# 原始二維陣列
b = a.ravel()  						# ravel() 傳回view
print('使用 ravel() 後的陣列 b：', b)
b[0] = 100  							# 修改 b[0]
print('修改 b 後的原始陣列 a：\n', a)
print('是否共享記憶體？', np.shares_memory(a, b))  	# True
  
a = np.array([[1, 2], [3, 4]])  		# 重新初始化a 
c = a.flatten()   					# flatten() 傳回copy
print('使用 flatten() 後的陣列 c：', c)
c[0] = 200  							# 修改 c[0]
print('修改 c 後的原始陣列 a：\n', a)
print('是否共享記憶體？', np.shares_memory(a, c))  	# False

使用 ravel() 後的陣列 b： [1 2 3 4]
修改 b 後的原始陣列 a：
 [[100   2]
 [  3   4]]
是否共享記憶體？ True
使用 flatten() 後的陣列 c： [1 2 3 4]
修改 c 後的原始陣列 a：
 [[1 2]
 [3 4]]
是否共享記憶體？ False


##### 9.3.2 增減陣列的軸（維度）

In [106]:
a = np.array([1, 2])

In [107]:
print(a[None, :])

[[1 2]]


In [108]:
print(a[:, None])

[[1]
 [2]]


In [109]:
a = np.array([[1, 2], [3, 4]])

In [110]:
print(a[None,:,:])

[[[1 2]
  [3 4]]]


In [111]:
print(a[:,None,:])

[[[1 2]]

 [[3 4]]]


In [112]:
b = np.array([[[1, 2], [3, 4]]])

In [126]:
print(b.squeeze())

[[1 2]
 [3 4]]


##### 9.3.3 陣列的分割與合併

In [113]:
a = np.arange(16).reshape(4, 4)

In [114]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [115]:
a1, a2=np.vsplit(a, 2)

In [116]:
print(a1)

[[0 1 2 3]
 [4 5 6 7]]


In [117]:
print(a2)

[[ 8  9 10 11]
 [12 13 14 15]]


In [118]:
print(np.hstack((a1, a2)))

[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [119]:
print(np.vstack((a1,[0,0,0,0])))

[[0 1 2 3]
 [4 5 6 7]
 [0 0 0 0]]


In [120]:
a=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8]])

In [121]:
np.split(a, 2, axis = 1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [122]:
np.split(a, [1, 3], axis = 1)

[array([[1],
        [5]]),
 array([[2, 3],
        [6, 7]]),
 array([[4],
        [8]])]

In [123]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [124]:
print(np.stack((a, b),axis = 0)) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [125]:
print(np.stack((a, b), axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [126]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])

In [127]:
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

##### 9.3.4 陣列分割與合併的應用

In [128]:
# ch9_6.py, 陣列的切割與重排
import numpy as np
mat = np.array([[4, 6, 1, 7, 4, 9],
                 [5, 0, 4, 2, 5, 8],
                 [0, 2, 1, 5, 7, 2],
                 [6, 8, 9, 3, 8, 6]])
 
# Step 1: 切成兩塊（2x6）
rows = np.vsplit(mat, 2)
 
# Step 2: 每塊切成三個 2x2
blocks = [np.hsplit(r, 3) for r in rows]

# Step 3: 每個 2x2 攤平成 1x4
flat = [b.reshape(1, 4) for grp in blocks for b in grp]

# Step 4: 垂直合併
out = np.concatenate(flat, axis=0)

print('重排後的新陣列:')
print(out)

重排後的新陣列:
[[4 6 5 0]
 [1 7 4 2]
 [4 9 5 8]
 [0 2 6 8]
 [1 5 9 3]
 [7 2 8 6]]
