### 第十章 NumPy 的數學運算

#### 10.1 基本運算

##### 10.1.1 常數與數學函數

In [1]:
import numpy as np

In [2]:
np.pi

3.141592653589793

In [3]:
np.inf/np.inf

nan

In [4]:
np.e

2.718281828459045

In [5]:
a = np.array([0, 1, 2])

In [6]:
a + 3

array([3, 4, 5])

In [7]:
a ** 2

array([0, 1, 4])

In [8]:
a + [4, 5, 6]

array([4, 6, 8])

In [9]:
np.mod([78, 80, 93], 2)

array([0, 0, 1])

In [10]:
np.round(12.45, 1)

np.float64(12.4)

In [11]:
np.maximum([4, 5, 4], [1, 2, 7])

array([4, 5, 7])

In [12]:
np.ceil([0.1, 4.7, 3.01])

array([1., 5., 4.])

In [13]:
np.floor([5.38, 4.99, 3.01])

array([5., 4., 3.])

In [14]:
np.log2(1024)

np.float64(10.0)

In [15]:
np.sqrt([2, 3])

array([1.41421356, 1.73205081])

In [16]:
np.sin(np.radians(90))

np.float64(1.0)

In [17]:
np.exp([-3, 1])

array([0.04978707, 2.71828183])

##### 10.1.2 邏輯運算函數

In [18]:
a = np.array([0, 2, 3])

In [19]:
b = np.array([0, 3, 0])

In [20]:
np.array_equal(a, b)

False

In [21]:
np.logical_and(a, b)

array([False,  True, False])

In [22]:
np.logical_xor(a, b)

array([False, False,  True])

In [23]:
np.logical_not(a)

array([ True, False, False])

##### 10.1.3 陣列的顯示設定

In [1]:
# ch10_1.py set_printoptions() 的範例
import numpy as np
a = np.array([1440, 123.89, 0.123])
b = np.sin([0.5, 1, 3])
 
print('預設輸出：')
print(a)
print(b)
 
# 設定新的格式選項
np.set_printoptions(precision = 2, suppress = True)
 
print('套用設定後的輸出：')
print(a)
print(b)
np.set_printoptions(precision = 8, suppress = False)  # 設回預設值

預設輸出：
[1.4400e+03 1.2389e+02 1.2300e-01]
[0.47942554 0.84147098 0.14112001]
套用設定後的輸出：
[1440.    123.89    0.12]
[0.48 0.84 0.14]


In [2]:
# ch10_2.py, printoptions() 搭配 with 區塊
import numpy as np
a = np.sin([0.5, 1, 3])

with np.printoptions(precision = 3):     # 設定小數點精度為 3 位
    print(a)   # 在區塊內的 print() 會使用這個精度

print(a)  # 這裡的 print() 會使用預設精度

[0.479 0.841 0.141]
[0.47942554 0.84147098 0.14112001]


#### 10.2 陣列的進階運算處理

##### 10.2.1 運算與條件選取

In [27]:
a = np.array([1, 5, 0])

In [28]:
a.sum()

np.int64(6)

In [29]:
np.sum(a)

np.int64(6)

In [30]:
a.max()

np.int64(5)

In [31]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [32]:
a.sum()

np.int64(45)

In [33]:
a.sum(axis = 0)

array([12, 15, 18])

In [34]:
np.min(a)

np.int64(1)

In [35]:
np.max(a, axis =1)

array([3, 6, 9])

In [36]:
np.all([0, 1, 2])

np.False_

In [37]:
np.any([False, False, True])

np.True_

In [38]:
# ch10_3.py, all() 和 any() 的應用
import numpy as np
# 每列代表不同時間點的溫度
temps = np.array([
    [25, 30],   # 時間點0，正常
    [15, 18],   # 時間點1，全部正常
    [12, 92]    # 時間點2，機台1過熱 (從0開始數)
]) 

# 檢查所有溫度是否正常
all_ok = np.all((temps >= 10) & (temps <= 90))
print('全部正常？', all_ok)
 
# 找出每個時間點是否有任何異常
has_problem = np.any((temps < 10) | (temps > 90), axis=1)
print('有異常時間點：', has_problem)

全部正常？ False
有異常時間點： [False False  True]


##### 10.2.2 數值位置查找與索引轉換

In [39]:
a = np.array([3, 7, 9, 0])

In [41]:
np.argmax(a)

np.int64(2)

In [42]:
a.argmax()

np.int64(2)

In [43]:
a = np.array([[4, 3, 8, 1],
              [3, 9, 0, 2],
              [6, 9, 7, 5]])

In [44]:
a.argmax(axis = 0)

array([2, 1, 0, 2])

In [45]:
a.argmax(axis = 1)

array([2, 1, 1])

In [46]:
a.argmin()

np.int64(6)

In [47]:
np.unravel_index(6, a.shape)

(np.int64(1), np.int64(2))

In [48]:
a.argmax()

np.int64(5)

In [49]:
np.ravel_multi_index([1,2],(3,4))

np.int64(6)

In [50]:
np.unravel_index([0, 3, 7], (3, 4))

(array([0, 0, 1]), array([0, 3, 3]))

In [51]:
np.ravel_multi_index([[0, 0, 1],[0, 3, 3]], (3, 4))

array([0, 3, 7])

In [52]:
a = np.array([7, 3, 5])

In [53]:
np.where(a > 4)

(array([0, 2]),)

In [54]:
np.where(a > 4, 99, a)

array([99,  3, 99])

In [56]:
np.where(a > 4,[5, 6, 7],[8, 9, 0])

array([5, 9, 7])

In [57]:
a = np.array([[4, 3, 7],
              [5, 1, 2]])

In [58]:
np.where(a % 2 == 0)

(array([0, 1]), array([0, 2]))

In [59]:
np.where(a % 2 == 0, 0, a)

array([[0, 3, 7],
       [5, 1, 0]])

In [60]:
# ch10_4.py, where() 與索引轉換函數應用
import numpy as np
scores = np.array([		# 甜甜圈得分資料（3 家店，4 種口味）
    [ 87, 100,  92, 75],	# 第0號店
    [100,  85, 100, 60], 	# 第1號店
    [ 88,  90,  87, 73] 	# 第2號店
])
max_pos = np.where(scores == 100)  		# 找出所有滿分的 index

# 轉換成一維索引（方便儲存, 轉換後的值應為 [1, 4, 6]）
indices = np.ravel_multi_index(max_pos, scores.shape)

# 從一維還原回 (店號, 口味)
unraveled = np.unravel_index(indices, scores.shape)
for store, flavor in zip(*unraveled):
    print(f'第 {store} 號店，第 {flavor} 種口味')

第 0 號店，第 1 種口味
第 1 號店，第 0 種口味
第 1 號店，第 2 種口味


In [61]:
a = np.array([[3, 4, 5, 4],
              [6, 0, 8, 0],
              [6, 0, 8, 0]])

In [62]:
np.unique(a, axis = 1)

array([[3, 4, 5],
       [6, 0, 8],
       [6, 0, 8]])

In [63]:
np.unique(a)

array([0, 3, 4, 5, 6, 8])

#### 10.3 統計處理與資料排序

##### 10.3.1 統計處理

In [64]:
a = np.array([[3, 4, 5],
              [6, 1, 8]])

In [65]:
a.mean()

np.float64(4.5)

In [66]:
a.mean(axis = 1)

array([4., 5.])

In [67]:
np.median(a)

np.float64(4.5)

In [68]:
a.std()

np.float64(2.217355782608345)

In [69]:
a.var(axis = 0)

array([2.25, 2.25, 2.25])

In [70]:
np.percentile(a, 50)

np.float64(4.5)

##### 10.3.2 排序處理

In [71]:
a = np.array([17, 88, 12, 93])

In [72]:
np.sort(a)

array([12, 17, 88, 93])

In [73]:
a

array([17, 88, 12, 93])

In [74]:
a.sort()

In [75]:
a

array([12, 17, 88, 93])

In [76]:
a[::-1]

array([93, 88, 17, 12])

In [77]:
a = np.array([71, 77, 25, 19])

In [78]:
idx = np.argsort(a); idx

array([3, 2, 0, 1])

In [79]:
b = np.sort(a); b

array([19, 25, 71, 77])

In [80]:
c = np.zeros(4, dtype = int)

In [81]:
c[idx] = b; c

array([71, 77, 25, 19])

In [82]:
a = np.array([[7, 8, 3],
              [4, 1, 9]])

In [83]:
np.sort(a)

array([[3, 7, 8],
       [1, 4, 9]])

In [84]:
np.sort(a, axis = 0)

array([[4, 1, 3],
       [7, 8, 9]])

In [85]:
np.sort(a, axis = None)

array([1, 3, 4, 7, 8, 9])

In [86]:
np.argsort(a, axis = 0)

array([[1, 1, 0],
       [0, 0, 1]])

In [87]:
a[0,:]

array([7, 8, 3])

In [88]:
np.argsort(a[0,:])

array([2, 0, 1])

In [89]:
a[:,np.argsort(a[0,:])]

array([[3, 7, 8],
       [9, 4, 1]])

In [90]:
# ch10_5.py, 步數紀錄分析
import numpy as np
steps = np.array([8500, 9000, 7600, 8800, 5300])
days = np.array(['Mon', 'Tue', 'Wed', 'Thu', 'Fri'])
 
print('平均步數：', np.mean(steps))			
print('中位數：', np.median(steps))
print('標準差：', np.std(steps))
 
# 最多與最少步數及星期
max_idx = np.argmax(steps)
min_idx = np.argmin(steps)
print(f'最多步數：{steps[max_idx]}({days[max_idx]})')
print(f'最少步數：{steps[min_idx]}({days[min_idx]})')
 
# 步數排序（橫列輸出）
idx = np.argsort(steps)
result = [f'{days[i]}:{steps[i]}' for i in idx]
print('步數排序：', result)

平均步數： 7840.0
中位數： 8500.0
標準差： 1357.350360076572
最多步數：9000(Tue)
最少步數：5300(Fri)
步數排序： ['Fri:5300', 'Wed:7600', 'Mon:8500', 'Thu:8800', 'Tue:9000']


#### 10.4 數學矩陣的相關運算

##### 10.4.1 矩陣常用的運算

In [91]:
a = np.array([0, 1, 2])

In [92]:
b = np.array([3, 4, 5])

In [93]:
vr = np.array([[3, 4, 5]])

In [94]:
m = np.array([[2, 3, 1, 1],
              [3, 0, 1, 0],
              [1, 0, 3, 2]])

In [95]:
np.dot(a, b)

np.int64(14)

In [96]:
np.dot(2, m)

array([[4, 6, 2, 2],
       [6, 0, 2, 0],
       [2, 0, 6, 4]])

In [97]:
np.matmul(vr, m)

array([[23,  9, 22, 13]])

In [98]:
vr @ m

array([[23,  9, 22, 13]])

##### 10.4.2 使用 numpy.linalg 模組

In [99]:
from numpy import linalg

In [100]:
m = np.array([[1, 4], [3, -1]])

In [101]:
b = np.array([[6], [5]])

In [102]:
linalg.det(m)

np.float64(-13.0)

In [103]:
linalg.inv(m)

array([[ 0.08,  0.31],
       [ 0.23, -0.08]])

In [104]:
m @ linalg.inv(m)

array([[1., 0.],
       [0., 1.]])

In [105]:
linalg.solve(m, b)

array([[2.],
       [1.]])

In [106]:
linalg.eig(m)

EigResult(eigenvalues=array([ 3.61, -3.61]), eigenvectors=array([[ 0.84, -0.66],
       [ 0.55,  0.75]]))

In [107]:
linalg.eigvals(m)

array([ 3.61, -3.61])

In [108]:
m = np.array([[ 1, 2],
              [ 3, 5],
              [-1, 1]])

In [109]:
b = np.array([[4, 8 , 5]]).T

In [110]:
linalg.lstsq(m, b)

(array([[-2.14],
        [ 2.91]]),
 array([0.12]),
 np.int32(2),
 array([6.25, 1.38]))

#### 10.5 廣播運算

##### 10.5.1 廣播的基本運算

In [111]:
a = np.array([[0, 1, 2],
              [3, 4, 5]])

In [112]:
b = np.array([[1, 1, 1],
              [1, 1, 1]])

In [113]:
a + b

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
a = np.array([[0],
              [1],
              [2]])

In [117]:
b = np.array([[3, 4, 5, 6]])

In [118]:
a + b

array([[3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

##### 10.5.2 廣播運算的應用

In [119]:
# ch10_6.py, 找出最小距離的兩個點, for 迴圈版
import numpy as np
pa = np.array([[2, 4, 5],			# pa 的x 座標
                 [3, 3, 4]])			# pa 的y 座標
pb = np.array([[3, 4, 5, 6],		# pb 的x 座標
                 [0, 7, 2, 1]])		# pb 的y 座標
d2 = np.zeros((pa.shape[1], pb.shape[1]))
 
for i in range(pa.shape[1]):      	# pa 中的點
    for j in range(pb.shape[1]):  	# pb 中的點
        d2[i,j] = np.sum((pa[:, i] - pb[:, j])**2)
 
print(d2)
ma, mb = np.unravel_index(np.argmin(d2), d2.shape)
print(f'pa: {ma}, pb: {mb}, 距離平方為：{d2[ma, mb]:.2f}')

[[10. 20. 10. 20.]
 [10. 16.  2.  8.]
 [20. 10.  4. 10.]]
pa: 1, pb: 2, 距離平方為：2.00


In [120]:
# ch10_7.py, 找出最小距離的兩個點, 廣播版
import numpy as np
pa = np.array([[2, 4, 5],     		# x 座標 (3 個點)
                 [3, 3, 4]])    		# y 座標
pb = np.array([[3, 4, 5, 6],     	# x 座標 (4 個點)
                 [0, 7, 2, 1]])    	# y 座標

# 使用 broadcasting 計算差值, shape: (2, 3, 4)
diff = pa[:, :, None] - pb[:, None, :]

# 將diff平方後加總，得到距離平方陣列, shape: (3, 4)
d2 = np.sum(diff**2, axis=0)

# 找出距離平方最小的位置
ma, mb = np.unravel_index(np.argmin(d2), d2.shape)
print(f'pa: {ma}, pb: {mb}, 距離平方為：{d2[ma, mb]:.2f}')

pa: 1, pb: 2, 距離平方為：2.00


In [121]:
# ch10_8.py, 迴圈和廣播所需時間的比較
import numpy as np
from time import time					# 載入time函數
def dist_for(pa, pb):  				#  for 迴圈版本
    d2 = np.zeros((pa.shape[1], pb.shape[1]))
    for i in range(pa.shape[1]):      	# a 中的點
        for j in range(pb.shape[1]):  	# b 中的點
            d2[i,j] = np.sum((pa[:, i] - pb[:, j])**2)

def dist_broadcast(pa, pb):   			# 廣播版本
    diff = pa[:, :, np.newaxis] - pb[:, np.newaxis, :]
    d2 = np.sum(diff**2, axis=0)

np.random.seed(0)
pa = np.random.randint(0, 100, size=(2, 1000))  # 1000 個點
pb = np.random.randint(0, 100, size=(2, 1200))  # 1200 個點
 
start = time()      		# 測試 for 迴圈版本
dist_for(pa, pb)  
print(f'[迴圈版本] 花費時間：{time() - start:.4f} 秒')
 
start = time()      		# 測量 broadcasting 版本
dist_broadcast(pa, pb)
print(f'[廣播版本] 花費時間：{time() - start:.4f} 秒')

[迴圈版本] 花費時間：25.5666 秒
[廣播版本] 花費時間：0.0288 秒


#### 10.6 儲存 NumPy 陣列

In [122]:
a = np.array([98, 12, 450], 
             dtype=np.int32)

In [123]:
z = a.tobytes()

In [124]:
len(z)

12

In [125]:
np.frombuffer(z, dtype=np.int32)

array([ 98,  12, 450], dtype=int32)

In [126]:
a = np.array([2.15, 3.14, 4.15])

In [127]:
np.save('test', a)

In [128]:
np.load('test.npy')

array([2.15, 3.14, 4.15])

In [129]:
a2 = np.array(['Python'],
              dtype= object)

In [130]:
np.save('test2', a2)

In [131]:
np.load('test2.npy',
        allow_pickle = True)

array(['Python'], dtype=object)

In [132]:
width = np.array([21, 20, 20])

In [133]:
height = np.array([172, 183, 176])

In [134]:
np.savez('example', 
         w = width, h = height)

In [135]:
npzfile = np.load('example.npz')

In [136]:
npzfile['w']

array([21, 20, 20])

In [137]:
npzfile['h']

array([172, 183, 176])